version: "3.7"
services:
  elasticsearch:
    image: elasticsearch:7.17.2
    container_name: elasticsearch
    user: root
    environment:
      cluster.name: elasticsearch
      discovery.type: single-node
    ports:
      - "9200:9200"
    volumes:
      - esdata1:/usr/share/elasticsearch/data

  logstash:
    image: logstash:7.17.2
    container_name: logstash
    command: logstash -f /etc/logstash/conf.d/logstash.conf
    ports:
      - "5000:5000"
    depends_on:
      - elasticsearch
    links:
      - elasticsearch
    volumes:
      - ./config/logstash:/etc/logstash/conf.d

  kibana:
    image: kibana:7.17.2
    container_name: kibana
    environment:
      ELASTICSEARCH_USERNAME: "elastic"
      ELASTICSEARCH_PASSWORD: "test123"
      ELASTICSEARCH_HOSTS: "http://elasticsearch:9200"
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    links:
      - elasticsearch
    volumes:
      - ./config/kibana/kibana.yml:/usr/share/kibana/config/kibana.yml

volumes:
  esdata1:
    driver: local